default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: red-badger_development

test:
  <<: *default
  database: red-badger_test

production:
  <<: *default
  database: red-badger_production
  username: red-badger
  password: <%= ENV['RED-BADGER_DATABASE_PASSWORD'] %>
